console.log(__dirname);
var path = require('path');
console.log('join');
console.log(path.join(__dirname, './a'));
console.log(path.join(__dirname, 'a/b'));
console.log(path.join('/foo', 'bar', 'baz/asdf', '/dfd', 'a', '..'));
console.log(path.join('/foo', 'bar', 'baz/asdf', '/dfd', '/a'));
console.log(path.join('/foo', 'bar', 'baz/asdf', '/dfd', '../a'));
console.log('resolve');
console.log(path.resolve(__dirname, 'a/b'));
console.log(path.resolve('/foo/bar', '/tmp/file/'));
console.log(path.resolve('/foo/bar', './tmp/file/'));
console.log(path.resolve('/foo/bar', '../tmp/file/'));
console.log(path.resolve('/foo/bar', 'tmp/file/'));
console.log(path.resolve('/foo', '/bar', 'baz'));
console.log(path.resolve('/foo', './bar', 'baz'));
console.log(path.resolve('./a', './b'));
console.log(path.resolve('/a', './b'));
console.log(path.resolve('/a', '../b'));
console.log(path.resolve('a', '../b'));
console.log(path.resolve('/'));
console.log(path.resolve('../'));
console.log(path.resolve(''));